version: '3.7'

services:

  db:
    image: mysql:8.0.25
    container_name: ekar-test
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ekar
      MYSQL_DATABASE: ekar
      MYSQL_USER: ekar
      MYSQL_PASSWORD: ekar

    ports:
      - 3306:3306

